version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - REPOSITORY_URI=318147513112.dkr.ecr.us-east-2.amazonaws.com/projettest
      - IMAGE_TAG=1.2
      - eval $(aws ecr get-login --region us-east-2 --no-include-email | sed 's|https://||')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 318147513112.dkr.ecr.us-east-2.amazonaws.com/projettest:$IMAGE_TAG
