version: 0.2

phases:
  install: 
    runtime-versions:
      php: 7.3
  pre_build: # commands to be run before build
    commands:
    - echo Logging in to Amazon ECR....
    - aws --version
    # login to Elastic container registry
    - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 318147513112.dkr.ecr.us-east-2.amazonaws.com
    - REPOSITORY_URI=318147513112.dkr.ecr.us-east-2.amazonaws.com/testrepo
    - IMAGE_TAG=1.2
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t $REPOSITORY_URI:latest .
    - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker image ls -a
      - docker push $REPOSITORY_URI:$IMAGE_TAG 
